### ISSUE TITLE
Can't reproduce known 2x possible issues in plugin

### ISSUE THREAD

**Issue by richardevcom** [richardevcom/add-polylang-support-for-customizer#2]
### Discussed in https://github.com/richardevcom/add-polylang-support-for-customizer/discussions/1

<div type='discussions-op-text'>

<sup>Originally posted by **richardevcom** January 18, 2022</sup>
Heyo 👋 

[So here are some errors/issues that couldn't be reproduced](https://wordpress.org/support/plugin/add-polylang-support-for-customizer/), yet there are some reports about them in Support forum.

1. **Plugin asks to be activated** - There have been 2 reports, that occasionally plugins just asks to be activated (doesn't seem to be activated - can't find correct Polylang index file pathing possibly!? [Here is the last source of issue](https://wordpress.org/support/topic/polylang-plugin-must-be-activated-for-add-polylang-support-for-customizer-plugin/).
2. **Fatal error** - `Call to undefined function Richardevcom\Apsfc\pll_current_language()` has appeared also more than 2 times, but never could be reproduced or caught on dev environment. [Here is the last source of issue](https://wordpress.org/support/topic/fatal-error-3980/). Possibly issues with namespaces or function filter priority - maybe hooking it earlier will help?

If you can help in any way to test these out, reproduce then and document process, reason or possible solution, that would be awesome 🙏 </div>

**Comment by mateodemirlika** [comment]
Hi i just installed it and Fatal error occurred just simple installation and this error occurred

`Fatal error: Uncaught Error: Call to undefined function Richardevcom\Apsfc\pll_current_language() in /var/www/html/wp-content/plugins/add-polylang-support-for-customizer/includes/class-apsfc.php:136 Stack trace: #0 /var/www/html/wp-content/plugins/add-polylang-support-for-customizer/includes/class-apsfc.php(250): Richardevcom\Apsfc\Apsfc->get_custom_customizer_option() #1 /var/www/html/wp-includes/class-wp-hook.php(326): Richardevcom\Apsfc\Apsfc->on_option_theme_mods_get() #2 /var/www/html/wp-includes/plugin.php(205): WP_Hook->apply_filters() #3 /var/www/html/wp-includes/option.php(256): apply_filters() #4 /var/www/html/wp-includes/theme.php(1018): get_option() #5 /var/www/html/wp-includes/theme.php(1055): get_theme_mods() #6 /var/www/html/wp-content/plugins/bopea-function/inc/core.php(789): get_theme_mod() #7 /var/www/html/wp-content/plugins/bopea-function/bopea-function.php(22): include_once('...') #8 /var/www/html/wp-settings.php(545): include_once('...') #9 /var/www/html/wp-config.php(108): require_once('...') #10 /var/www/html/wp-load.php(50): require_once('...') #11 /var/www/html/wp-admin/admin.php(35): require_once('...') #12 /var/www/html/wp-admin/plugins.php(10): require_once('...') #13 {main} thrown in /var/www/html/wp-content/plugins/add-polylang-support-for-customizer/includes/class-apsfc.php on line 136`
